version: '3.8'

services:
  web:
    build: .
    restart: always
    command: >
      sh -c "
      alembic upgrade head &&
      uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./:/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  db:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env_db
    ports:
      - "5555:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6666:6379'

  rabbitmq:
    image: rabbitmq:3.13-rc-alpine
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5


  celery_worker:
    build: .
    restart: always
    volumes:
      - ./:/app/
    command: "celery -A src.menu.worker.celery_app worker"
    depends_on:
      web:
        condition: service_started

  celery_beat:
    build: .
    restart: always
    volumes:
      - ./:/app/
    command: "celery -A src.menu.worker.celery_app beat"
    depends_on:
      celery_worker:
        condition: service_started

volumes:
  postgres_data:
