version: '3.8'

services:
  web_test:
    build: .
    restart: always
    command: >
      sh -c "
      alembic upgrade head &&
      uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - menu_test
    volumes:
      - ./:/app/
    env_file:
      - ./.env_test
    depends_on:
      db_test:
        condition: service_healthy

  db_test:
    image: postgres:15.1-alpine
    restart: always
    networks:
      - menu_test
    env_file:
      - ./.env_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    networks:
      - menu_test

networks:
  menu_test:
    driver: bridge
