version: '3.8'

services:
  web:
    build: .
    restart: always
    volumes:
      - ./:/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env_db
    ports:
      - "5555:5432"

volumes:
  postgres_data:
